#!/bin/bash

#ensures that no args or options have been passed
if [ $# -gt 0 ]
then
        echo "No arguments/options are allowed for this script!"
else

        if [ -z $TRASH ]
        then
                echo "The enironmental variable \"TRASH\" could not be located"

                #this is redundant, but could come in hand for future upgrades
                exit 1
        else
		#calling a "ls -l" on the entire garbage directory
		/bin/ls -l $TRASH
	fi
fi

